sudo: true
language: python
python: 3.5
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy

install:
  - pip install -U setuptools pip sphinx tox

script:
  - sudo update-ca-certificates
  - ./bin/test_standalone.sh
  - tox -e $TOX_ENV
  - ./bin/check_readme.sh

branches:
  except:
    - standalone
